#!/usr/bin/python
import os, sys

from kdecore import KCmdLineArgs

from useless.kdebase.error import excepthook

from dboxpykde.kdelib.application import MainApplication, AboutData
from dboxpykde.kdelib.mainwindow import MainWindow

from dboxpykde.dosbox import Dosbox
#from dboxpykde.kdelib.base import excepthook
from dboxpykde.kdelib.wizard import DboxPykdeWizard

if __name__ == '__main__':
    os.environ['_USELESS_DB_BACKEND'] = 'sqlite'
    aboutData = AboutData()
    # I don't understand this part
    KCmdLineArgs.init(sys.argv, aboutData)
    sys.excepthook = excepthook
    #raise StandardError, 'testing an error'

    # setup application
    app = MainApplication()
    use_wizard = False
    if hasattr(app, 'myconfig'):
        # setup dcop and register the application
        dcop = app.dcopClient()
        appid = dcop.registerAs('dosbox-pykde')
        if app.upgrade_to_db_required:
            app.convert_all_xml_to_db()
        win = MainWindow(None)
        win.show()
    elif use_wizard:
        win = DboxPykdeWizard(None)
        win.show()
    else:
        app.generate_default_config()
        app.generate_main_objects()
        # setup dcop and register the application
        dcop = app.dcopClient()
        appid = dcop.registerAs('dosbox-pykde')
        if app.upgrade_to_db_required:
            app.convert_all_xml_to_db()
        win = MainWindow(None)
        win.show()
        
    # set main window in application
    app.setMainWidget(win)
    # run the application
    app.exec_loop()

    
